---
title: "Day 25 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(igraph)
library(ggplot2)
library(ggraph)
library(reshape2)
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```


It's a graph!!!!!!!!

```{r}
 input<-read_lines("Day25Sample.txt")
# input2<-read_lines("Day25Sample2.txt")
# input3<-read_lines("Day25Sample3.txt")
# input4<-read_lines("Day25Sample4.txt")

```

```{r}
starchart<-list()
for(i in 1:length(input)){
  star<-as.numeric(unlist(str_split(input[i],",")))
  starchart<-c(starchart,list(star))}
```

turn a list of stars into a map
```{r}
mapthestars<-function(sc){
  staredge<-matrix(ncol=2,nrow=0)
  #### do a simple loop so that every point gets included
  for(i in 1:length(sc)){
    staredge<-rbind(staredge,c(str_flatten(starchart[[i]],collapse=" "),
                               str_flatten(starchart[[i]],collapse=" ")))}
  #### graph the actual points that connect to each other
  for(i in 1:(length(sc)-1)){
    for(j in (i+1):length(sc)){
      if(sum(abs(sc[[i]]-sc[[j]]))<=3){
        staredge<-rbind(staredge,c(str_flatten(starchart[[i]],collapse=" "),
                                   str_flatten(starchart[[j]],collapse=" ")))}}}
  starmap<-simplify(graph_from_edgelist(staredge,directed=FALSE))
  cat("There are ",count_components(starmap),"constellations.\n")
  starmap}
```


```{r}
sm<-mapthestars(starchart)
```


```{r}
ggraph(sm,layout="kk")+
  geom_edge_link()+
  geom_node_point()

```
