---
title: "Day 14 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

```{r}
input<-c(9,5,18,2018)#sample
```

```{r}
chocolate10<-function(n){
  e1<-1
  e2<-2
  ### make the scoreboard a dictionary
  scoreboard<-dict()
  scoreboard$set(1,3)
  scoreboard$set(2,7)
  ### allow appending the size to the end
  scsize<-scoreboard$size()
  while(scsize<(n+10)){
    ### for whatever reason, there's an integer/double problem
    r1<-scoreboard$get(as.double(e1))
    r2<-scoreboard$get(as.double(e2))
    ### add the two numbers together
    x<-as.numeric(unlist(str_split(scoreboard$get(as.double(e1))+scoreboard$get(as.double(e2)),"")))
    ### add the numerals to the end of the scoreboard
    for(i in 1:length(x)){
      scoreboard$set(as.double(scsize+i),x[i])}
    ### move the elf recipe position
    e1<-e1+r1+1
    e2<-e2+r2+1
    scsize<-scoreboard$size()
    while(e1>scsize){e1<-e1-scsize}
    while(e2>scsize){e2<-e2-scsize}
  }
  
  ### grab the last 10 numbers
  nxt10<-c()
  for(i in (n+1):(n+10)){
    nxt10<-c(nxt10,scoreboard$get(as.double(i)))}
  ### return
  str_flatten(nxt10)}
```

```{r}
sapply(input,chocolate10)
```





```{r,eval=FALSE}
part1<-chocolate10(MY INPUT)
part1

```
## Part 2

Mostly, use the same code, but this time keep a quick vector to see when/where you match the input



```{r}
recipefinder<-function(n){
  n<-as.numeric(unlist(str_split(as.character(n),"")))
  e1<-1
  e2<-2
  ### make the scoreboard a dictionary
  scoreboard<-dict()
  scoreboard$set(1,3)
  scoreboard$set(2,7)
  ##
  cmpr<-c(rep(100,(length(n)-2)),3,7)
  ### allow appending the size to the end
  scsize<-scoreboard$size()
  while(TRUE){
    ### for whatever reason, there's an integer/double problem
    r1<-scoreboard$get(as.double(e1))
    r2<-scoreboard$get(as.double(e2))
    ### add the two numbers together
    x<-as.numeric(unlist(str_split(scoreboard$get(as.double(e1))+scoreboard$get(as.double(e2)),"")))
    ### add the numerals to the end of the scoreboard
    for(i in 1:length(x)){
      scoreboard$set(as.double(scsize+i),x[i])
      cmpr<-as.numeric(c(cmpr[-1],x[i]))
      if(all(cmpr==n)){return(scoreboard$size()-length(n))}}
    ### move the elf recipe position
    e1<-e1+r1+1
    e2<-e2+r2+1
    scsize<-scoreboard$size()
    while(e1>scsize){e1<-e1-scsize}
    while(e2>scsize){e2<-e2-scsize}}
  scsize-length(n)}
```


```{r}
p2<-c(51589,"01245",92510,59414)#sample
sapply(p2,recipefinder)
```
```{r,eval=FALSE}
recipefinder(MY INPUT)
``` 
